//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileModification.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileModification.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write file..
        /// </summary>
        internal static string FileProcessor_CannotWriteFile {
            get {
                return ResourceManager.GetString("FileProcessor_CannotWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine processor for S3 object. Check metadata with key {0}..
        /// </summary>
        internal static string ProcessorSelection_FailedToDetermineProcessor {
            get {
                return ResourceManager.GetString("ProcessorSelection_FailedToDetermineProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy object failed..
        /// </summary>
        internal static string S3Handler_CopyObjectFailed {
            get {
                return ResourceManager.GetString("S3Handler_CopyObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket name is null or empty..
        /// </summary>
        internal static string S3Validation_BucketNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("S3Validation_BucketNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination bucket name and destination object key cannot be empty..
        /// </summary>
        internal static string S3Validation_CopyObject_DestinationIsNullOrEmpty {
            get {
                return ResourceManager.GetString("S3Validation_CopyObject_DestinationIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source bucket name and source object key cannot be empty..
        /// </summary>
        internal static string S3Validation_CopyObject_SourceIsNullOrEmpty {
            get {
                return ResourceManager.GetString("S3Validation_CopyObject_SourceIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object key is null or empty..
        /// </summary>
        internal static string S3Validation_KeyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("S3Validation_KeyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata value is null or empty. Processor cannot be selected without value..
        /// </summary>
        internal static string S3Validation_MetadataValueIsNullOrEmpty {
            get {
                return ResourceManager.GetString("S3Validation_MetadataValueIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata with key {0} not found, processor cannot be selected without {0} metadata entry..
        /// </summary>
        internal static string S3Validation_MetadataWithTypeCodeKeyNotFound {
            get {
                return ResourceManager.GetString("S3Validation_MetadataWithTypeCodeKeyNotFound", resourceCulture);
            }
        }
    }
}
